platform :ios, '9.0'

target 'PlumeWeather' do

  use_frameworks!
  pod 'Alamofire'
  pod 'OAuthSwiftAlamofire'

  target 'PlumeWeatherTests' do
    inherit! :search_paths
  end

  target 'PlumeWeatherUITests' do
    inherit! :search_paths
  end

end
